apiVersion: v1
kind: Service
metadata:
  name: weather-api-service
  labels:
    app: weather-api
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      name: http
  selector:
    app: weather-api
---
apiVersion: v1
kind: Service
metadata:
  name: weather-frontend-service
  labels:
    app: weather-frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      name: http
  selector:
    app: weather-frontend